name: CI + Deploy to Vercel

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project with secrets
        run: CI=false npm run build
        env:
          REACT_APP_TEST_RAZORPAY_KEY_ID: ${{ secrets.REACT_APP_TEST_RAZORPAY_KEY_ID }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy prebuilt app to Vercel
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN --confirm
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
